project_id = "jjutqhougypcqtubmfvy"

[functions.analyze-journal]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.translate-text]
verify_jwt = false
